In [1]:
from nltk import Tree
import cPickle, codecs
from zipfile import ZipFile
import numpy as np
from collections import defaultdict

In [4]:
train_tree_path = '../assignment3/trees/train.txt'
valid_tree_path = '../assignment3/trees/dev.txt'
test_tree_path = '../assignment3/trees/test.txt'

wv_path = '../../data/glove.840B.300d.zip'
wv_filename = 'glove.840B.300d.txt'
wv_size = 300

output_path = 'tmp/words.txt'
dict_path = '_data/dict.pkl'
embed_path = 'tmp/embeddings.pkl'
word_info_path = 'tmp/word_info.pkl'


with codecs.open(test_tree_path, encoding='utf-8') as f:
    for line in f:
        print line
        t = Tree.fromstring(line)
        print t[0][0][0]
        print t[1]
        break

(2 (3 (3 Effective) (2 but)) (1 (1 too-tepid) (2 biopic)))

Effective
(1 (1 too-tepid) (2 biopic))


In [5]:
import codecs

s = "I look like a string, but I'm actually a sequence of bytes. \xe2\x9d\xa4"
ss = codecs.decode(s, 'utf-8')

print ss

I look like a string, but I'm actually a sequence of bytes. ❤


In [5]:
a = np.arange(25).reshape((5, 5))
print a

print a[0:2, 0:2], np.sum(a[0:2, 0:2])
print a[0:2, 3:5]
print a[3:5, 0:2]
print a[3:5, 3:5]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1]
 [5 6]] 12
[[3 4]
 [8 9]]
[[15 16]
 [20 21]]
[[18 19]
 [23 24]]


In [5]:
a = np.asarray([0,0,1]).astype(np.int32)
b = np.asarray([0,1,1]).astype(np.int32)

print np.logical_or(a, b).astype(np.int32)

[0 1 1]
